// config.js
const completionCriteria = {
  "m0": [
    { title: 'P1', criteria: 'char', template: 'simple' },
    { title: 'P2', criteria: 'char', template: 'simple' },
    { title: 'P3', criteria: 'char', template: 'simple' },
    { title: 'P4', criteria: 'char', template: 'simple' },
    { title: 'S1', criteria: 'word', template: 'simple' },
    { title: 'P5', criteria: 'word', template: 'simple' },
    { title: 'P6', criteria: 'word', template: 'simple' },
    { title: 'P7', criteria: 'word', template: 'simple' },
    { title: 'P8', criteria: 'word', template: 'simple' },
    { title: 'S2', criteria: 'word', template: 'simple' },
  ],
  "m1": [
    { title: 'P1', criteria: 'char', template: 'simple' },
    { title: 'P2', criteria: 'char', template: 'simple' },
    { title: 'P3', criteria: 'char', template: 'simple' },
    { title: 'P4', criteria: 'word', template: 'simple' },
    { title: 'S1', criteria: 'word', template: 'simple' },
    { title: 'P5', criteria: 'word', template: 'simple' },
    { title: 'P6', criteria: 'word', template: 'simple' },
    { title: 'P7', criteria: 'word', template: 'simple' },
    { title: 'P8', criteria: 'word', template: 'simple' },
    { title: 'S2', criteria: 'word', template: 'simple' },
  ],
  "m2": [
    { title: 'P1', criteria: 'char', template: 'simple' },
    { title: 'P2', criteria: 'char', template: 'simple' },
    { title: 'P3', criteria: 'word', template: 'simple' },
    { title: 'P4', criteria: 'word', template: 'simple' },
    { title: 'S1', criteria: 'word', template: 'simple' },
    { title: 'P5', criteria: 'word', template: 'spell-and-check' },
    { title: 'P6', criteria: 'word', template: 'spell-and-check' },
    { title: 'P7', criteria: 'word', template: 'simple' },
    { title: 'P8', criteria: 'word', template: 'simple' },
    { title: 'S2', criteria: 'word', template: 'simple' },
  ],
  "m3": [
    { title: 'P1', criteria: 'word', template: 'spell-and-check' },
    { title: 'P2', criteria: 'word', template: 'spell-and-check' },
    { title: 'P3', criteria: 'sentence', template: 'simple' },
    { title: 'P4', criteria: 'sentence', template: 'simple' },
    { title: 'S1', criteria: 'sentence', template: 'simple' },
    { title: 'P5', criteria: 'word', template: 'spell-and-check' },
    { title: 'P6', criteria: 'sentence', template: 'spell-and-check' },
    { title: 'P7', criteria: 'sentence', template: 'simple' },
    { title: 'P8', criteria: 'sentence', template: 'simple' },
    { title: 'S2', criteria: 'sentence', template: 'simple' },
  ],
  "m4": [
    { title: 'P1', criteria: 'word', template: 'spell-and-check' },
    { title: 'P2', criteria: 'word', template: 'spell-and-check' },
    { title: 'P3', criteria: 'word', template: 'simple' },
    { title: 'P4', criteria: 'word', template: 'simple' },
    { title: 'S1', criteria: 'word', template: 'simple' },
    { title: 'P5', criteria: 'word', template: 'spell-and-check' },
    { title: 'P6', criteria: 'word', template: 'spell-and-check' },
    { title: 'P7', criteria: 'word', template: 'simple' },
    { title: 'P8', criteria: 'word', template: 'simple' },
    { title: 'S2', criteria: 'word', template: 'simple' }
  ],
  "m5": [
    { title: 'P1', criteria: 'sentence', template: 'simple' },
    { title: 'P2', criteria: 'sentence', template: 'simple' },
    { title: 'P3', criteria: 'sentence', template: 'simple' },
    { title: 'P4', criteria: 'sentence', template: 'simple' },
    { title: 'S1', criteria: 'sentence', template: 'simple' },
    { title: 'P5', criteria: 'sentence', template: 'simple' },
    { title: 'P6', criteria: 'sentence', template: 'simple' },
    { title: 'P7', criteria: 'sentence', template: 'simple' },
    { title: 'P8', criteria: 'sentence', template: 'simple' },
    { title: 'S2', criteria: 'sentence', template: 'simple' }
  ],
  "m6": [
    { title: 'P1', criteria: 'sentence', template: 'simple' },
    { title: 'P2', criteria: 'sentence', template: 'simple' },
    { title: 'P3', criteria: 'sentence', template: 'simple' },
    { title: 'P4', criteria: 'sentence', template: 'simple' },
    { title: 'S1', criteria: 'sentence', template: 'simple' },
    { title: 'P5', criteria: 'sentence', template: 'simple' },
    { title: 'P6', criteria: 'sentence', template: 'simple' },
    { title: 'P7', criteria: 'sentence', template: 'simple' },
    { title: 'P8', criteria: 'sentence', template: 'simple' },
    { title: 'S2', criteria: 'sentence', template: 'simple' }
  ],
  "m7": [
    { title: 'P1', criteria: 'sentence', template: 'simple' },
    { title: 'P2', criteria: 'sentence', template: 'simple' },
    { title: 'P3', criteria: 'paragraph', template: 'simple' },
    { title: 'P4', criteria: 'paragraph', template: 'simple' },
    { title: 'S1', criteria: 'paragraph', template: 'simple' },
    { title: 'P5', criteria: 'paragraph', template: 'simple' },
    { title: 'P6', criteria: 'paragraph', template: 'simple' },
    { title: 'P7', criteria: 'paragraph', template: 'simple' },
    { title: 'P8', criteria: 'paragraph', template: 'simple' },
    { title: 'S2', criteria: 'paragraph', template: 'simple' }
  ],
  "m8": [
    { title: 'P1', criteria: 'sentence', template: 'simple' },
    { title: 'P2', criteria: 'sentence', template: 'simple' },
    { title: 'P3', criteria: 'paragraph', template: 'simple' },
    { title: 'P4', criteria: 'paragraph', template: 'simple' },
    { title: 'S1', criteria: 'paragraph', template: 'simple' },
    { title: 'P5', criteria: 'paragraph', template: 'simple' },
    { title: 'P6', criteria: 'paragraph', template: 'simple' },
    { title: 'P7', criteria: 'paragraph', template: 'simple' },
    { title: 'P8', criteria: 'paragraph', template: 'simple' },
    { title: 'S2', criteria: 'paragraph', template: 'simple' }
  ],
  "m9": [
    { title: 'P1', criteria: 'sentence', template: 'simple' },
    { title: 'P2', criteria: 'sentence', template: 'simple' },
    { title: 'P3', criteria: 'paragraph', template: 'simple' },
    { title: 'P4', criteria: 'paragraph', template: 'simple' },
    { title: 'S1', criteria: 'paragraph', template: 'simple' },
    { title: 'P5', criteria: 'paragraph', template: 'simple' },
    { title: 'P6', criteria: 'paragraph', template: 'simple' },
    { title: 'P7', criteria: 'paragraph', template: 'simple' },
    { title: 'P8', criteria: 'paragraph', template: 'simple' },
    { title: 'S2', criteria: 'paragraph', template: 'simple' }
  ]
};

export default completionCriteria;
